version: '3.4'

services:
  data.aggregate.in.api:
    image: ei8works/data.aggregate.in.api:0.1.2
    build:
      context: .
      dockerfile: ./main/Port.Adapter/In/Api/Dockerfile
  data.aggregate.out.api:
    image: ei8works/data.aggregate.out.api:0.1.2
    build:
      context: .
      dockerfile: ./main/Port.Adapter/Out/Api/Dockerfile